# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-11 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import routing.models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0004_auto_20161211_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='country',
            field=django_countries.fields.CountryField(countries=routing.models.ITUCountries, max_length=2),
        ),
        migrations.AlterField(
            model_name='router',
            name='dns',
            field=models.CharField(default='no.hostname.provided', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='routerconnection',
            name='from_router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_router', to='routing.Router'),
        ),
        migrations.AlterField(
            model_name='routerconnection',
            name='to_router',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_router', to='routing.Router'),
        ),
    ]
