# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-11 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0005_auto_20170211_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='routertype',
            name='script',
            field=models.CharField(default='', max_length=50),
        ),
    ]
