# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-11 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0006_routertype_script'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
