# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0007_delete_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='lastSeen',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
