# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0008_router_lastseen'),
    ]

    operations = [
        migrations.AddField(
            model_name='routertype',
            name='ping_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='routertype',
            name='script',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
