# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0009_auto_20170212_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_ca.Certificate'),
        ),
    ]
