# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0002_country_countrycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='as',
            name='number',
            field=models.BigIntegerField(),
        ),
    ]
