# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-11 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipnetwork',
            name='size',
            field=models.PositiveSmallIntegerField(choices=[(32, '/32 (1 Host)'), (31, '/31 (2 Hosts)'), (30, '/30 (4 Hosts)'), (29, '/29 (8 Hosts)'), (28, '/28 (16 Hosts)'), (27, '/27 (32 Hosts)'), (26, '/26 (64 Hosts)'), (25, '/25 (128 Hosts)'), (24, '/24 (256 Hosts)')]),
        ),
    ]
